"""initial migration

Revision ID: d370df868d76
Revises: 
Create Date: 2025-11-21 13:26:24.115795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd370df868d76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('location_area', sa.String(length=100), nullable=False),
    sa.Column('prob_input', sa.String(length=50), nullable=True),
    sa.Column('sev_input', sa.String(length=50), nullable=True),
    sa.Column('comp_input', sa.String(length=50), nullable=True),
    sa.Column('prob_weight', sa.Integer(), nullable=False),
    sa.Column('sev_weight', sa.Integer(), nullable=False),
    sa.Column('comp_multiplier', sa.Float(), nullable=False),
    sa.Column('calculated_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('final_action', sa.Text(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('assessment_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_assessment_date'), ['assessment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_employee_id'), ['employee_id'], unique=False)

    op.create_table('risk_factor_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factor_id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('weights', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factor_id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('risk_matrix_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('action_suggestion', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('risk_matrix_rules', schema=None) as batch_op:
        batch_op.create_index('range_idx', ['min_score', 'max_score'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_matrix_rules', schema=None) as batch_op:
        batch_op.drop_index('range_idx')

    op.drop_table('risk_matrix_rules')
    op.drop_table('risk_factor_definitions')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessments_employee_id'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_assessment_date'))

    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
